[package]
name = "gfm_markdown_viewer"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
comrak.workspace = true
once_cell.workspace = true
reqwest.workspace = true
base64.workspace = true
selectable_text.workspace = true
syntax.workspace = true
ui.workspace = true
unicode-segmentation.workspace = true
tree-sitter.workspace = true
tree-sitter-html.workspace = true
