[package]
name = "reviu"
version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.bundle]
name = "Reviu"
identifier = "com.jorisgallot.reviu"
icon = ["assets/reviu.icns"]

[dependencies]
editor = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
ui = { workspace = true }
workspace = { workspace = true }
reqwest_client = { workspace = true }
sentry = { workspace = true }
percent-encoding = { workspace = true }

[build-dependencies]
embed-resource = { workspace = true }
