[package]
name = "workspace"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
editor = { workspace = true }
git = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
gfm_markdown_viewer = { workspace = true }
ui = { workspace = true }
dirs = { workspace = true }
rusqlite = { workspace = true }
syntax = { workspace = true }
smol = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
sha2 = { workspace = true }
sentry = { workspace = true }

[dev-dependencies]
git2 = { workspace = true }
gpui = { workspace = true, features = ["test-support"] }
