[package]
name = "editor"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
app_log = { workspace = true }
buffer = { workspace = true }
syntax = { workspace = true }
ui = { workspace = true }
gpui = { workspace = true }
unicode-segmentation = { workspace = true }
parking_lot = { workspace = true }
git = { workspace = true }
gpui-component = { workspace = true }
blake3 = { workspace = true }
gfm_markdown_viewer = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
gpui = { workspace = true, features = ["test-support"] }

[[bench]]
name = "performance"
harness = false

[lints]
workspace = true
