[package]
name = "syntax"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
tree-sitter-highlight.workspace = true
tree-sitter.workspace = true
tree-sitter-astro-next.workspace = true
tree-sitter-bash.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-json.workspace = true
tree-sitter-md.workspace = true
tree-sitter-css.workspace = true
tree-sitter-scss.workspace = true
tree-sitter-toml-ng.workspace = true
tree-sitter-html.workspace = true
tree-sitter-dockerfile.workspace = true
tree-sitter-xml.workspace = true
tree-sitter-python.workspace = true
tree-sitter-yaml.workspace = true
tree-sitter-vue.workspace = true
once_cell.workspace = true
