FROM node:24-alpine AS build

WORKDIR /app

RUN npm i -g corepack@latest && corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV PUBLIC_BACKEND_URL=https://api.reviu.dev

RUN pnpm build

FROM nginx:alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
