name: Deploy Landing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  landing_deploy:
    name: Landing - Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: landing/package.json
          cache: true

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: landing/package.json
          cache: pnpm
          cache-dependency-path: landing/pnpm-lock.yaml

      - name: Trigger Dokploy Deployment
        env:
          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
          DOKPLOY_LANDING_APP_ID: ${{ secrets.DOKPLOY_LANDING_APP_ID }}
        run: |
          curl -X 'POST' \
          'https://dokploy.jorisgallot.dev/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H "x-api-key: $DOKPLOY_API_KEY" \
          -H 'Content-Type: application/json' \
          -d "{
              \"json\":{
                  \"applicationId\": \"$DOKPLOY_LANDING_APP_ID\"
              }
          }"
